# Generated by Django 4.2.4 on 2023-09-15 22:40

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.events.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('value', models.IntegerField(default=0, verbose_name='wartość')),
            ],
            options={
                'verbose_name': 'licznik',
                'verbose_name_plural': 'liczniki',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                (
                    'introduction',
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='wprowadzenie'),
                ),
                (
                    'description',
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='opis'),
                ),
                (
                    'contents',
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name='zawartość wydarzenia'
                    ),
                ),
                (
                    'date_start',
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name='data rozpoczęcia'),
                ),
                (
                    'form_id',
                    models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='id formularza'),
                ),
                ('form_html', models.TextField(blank=True, null=True, verbose_name='kod html formularza')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='miasto')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='adres')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='miejsce')),
                (
                    'background_image',
                    models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='zdjęcie tła'),
                ),
            ],
            options={
                'verbose_name': 'wydarzenie',
                'verbose_name_plural': 'wydarzenia',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='wpis')),
                (
                    'description',
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='opis'),
                ),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='zdjęcie')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data publikacji')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='zdjęcie')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partnerzy',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='zdjęcie')),
            ],
            options={
                'verbose_name': 'zdjęcie',
                'verbose_name_plural': 'zdjęcia',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('price', models.IntegerField(default=0, verbose_name='cena')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='data rozpoczęcia')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='data zakończenia')),
            ],
            options={
                'verbose_name': 'koszt',
                'verbose_name_plural': 'koszty',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='imię i nazwisko')),
                (
                    'description',
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='opis'),
                ),
                ('image', models.ImageField(blank=True, null=True, upload_to='speakers/', verbose_name='zdjęcie')),
            ],
            options={
                'verbose_name': 'prelegent',
                'verbose_name_plural': 'prelegenci',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                (
                    'unique_code',
                    models.CharField(
                        default=apps.events.utils.generate_unique_code, max_length=50, unique=True, verbose_name='kod'
                    ),
                ),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data zgłoszenia')),
                ('is_paid', models.BooleanField(default=False, verbose_name='opłacone')),
                ('tpay_notification', models.JSONField(blank=True, null=True)),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='registrations',
                        to='events.event',
                        verbose_name='wydarzenie',
                    ),
                ),
            ],
            options={
                'verbose_name': 'zgłoszenie',
                'verbose_name_plural': 'zgłoszenia',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_speakers',
                        to='events.event',
                        verbose_name='wydarzenie',
                    ),
                ),
                (
                    'speaker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.speaker', verbose_name='prelegent'
                    ),
                ),
            ],
            options={
                'verbose_name': 'prelegent wydarzenia',
                'verbose_name_plural': 'prelegenci wydarzenia',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='costs',
                        to='events.event',
                        verbose_name='wydarzenie',
                    ),
                ),
                (
                    'price',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.price', verbose_name='koszt'
                    ),
                ),
            ],
            options={
                'verbose_name': 'cena wydarzenia',
                'verbose_name_plural': 'ceny wydarzenia',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('hours', models.CharField(blank=True, max_length=30, null=True, verbose_name='godzina')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plan/', verbose_name='zdjęcie')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plan_items',
                        to='events.event',
                        verbose_name='wydarzenie',
                    ),
                ),
                (
                    'speaker',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='events.speaker',
                        verbose_name='prelegent',
                    ),
                ),
            ],
            options={
                'verbose_name': 'punkt planu',
                'verbose_name_plural': 'punkty planu',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='wydarzenie'
                    ),
                ),
                (
                    'partner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.partner', verbose_name='partner'
                    ),
                ),
            ],
            options={
                'verbose_name': 'partner wydarzenia',
                'verbose_name_plural': 'partnerzy wydarzenia',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                (
                    'counter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.counter', verbose_name='licznik'
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='wydarzenie'
                    ),
                ),
            ],
            options={
                'verbose_name': 'licznik wydarzenia',
                'verbose_name_plural': 'liczniki wydarzenia',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='counters',
            field=models.ManyToManyField(blank=True, through='events.EventCounter', to='events.counter'),
        ),
        migrations.AddField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, through='events.EventPartner', to='events.partner'),
        ),
        migrations.AddField(
            model_name='event',
            name='prices',
            field=models.ManyToManyField(
                blank=True, through='events.EventPrice', to='events.price', verbose_name='ceny'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, through='events.EventSpeaker', to='events.speaker'),
        ),
    ]
