# Generated by Django 4.2.4 on 2023-09-16 14:22

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name='polityka prywatności'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='regulations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='regulamin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='counters',
            field=models.ManyToManyField(
                blank=True, through='events.EventCounter', to='events.counter', verbose_name='liczniki'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(
                blank=True, through='events.EventPartner', to='events.partner', verbose_name='partnerzy'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(
                blank=True, through='events.EventSpeaker', to='events.speaker', verbose_name='prelegenci'
            ),
        ),
        migrations.AlterField(
            model_name='eventcounter',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_counters',
                to='events.event',
                verbose_name='wydarzenie',
            ),
        ),
        migrations.AlterField(
            model_name='eventpartner',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_partners',
                to='events.event',
                verbose_name='wydarzenie',
            ),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_prices',
                to='events.event',
                verbose_name='wydarzenie',
            ),
        ),
    ]
