# Generated by Django 4.2.4 on 2023-09-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_event_privacy_policy_event_regulations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='kod')),
                (
                    'discount',
                    models.DecimalField(
                        decimal_places=2, help_text='wartość w zł', max_digits=5, verbose_name='zniżka'
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='discount_codes',
                        to='events.event',
                        verbose_name='wydarzenie',
                    ),
                ),
            ],
            options={
                'verbose_name': 'kod rabatowy',
                'verbose_name_plural': 'kody rabatowe',
            },
        ),
    ]
