# Generated by Django 4.2.4 on 2023-09-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='imię i nazwisko'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='responses',
            field=models.TextField(blank=True, null=True, verbose_name='odpowiedzi'),
        ),
    ]
