# Generated by Django 4.2.4 on 2023-09-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_registration_name_registration_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid_amount',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='kwota opłacona'
            ),
        ),
    ]
