# Generated by Django 4.2.4 on 2023-09-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_registration_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
