# Generated by Django 4.2.4 on 2023-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='strona facebook'),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='strona instagram'),
        ),
        migrations.AddField(
            model_name='event',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True, verbose_name='strona tiktok'),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='strona youtube'),
        ),
    ]
