# Generated by Django 4.2.4 on 2023-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0007_event_facebook_link_event_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='x_link',
            field=models.URLField(blank=True, null=True, verbose_name='strona twitter'),
        ),
    ]
