# Generated by Django 4.2.4 on 2024-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0011_event_max_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='promo_movie_html',
            field=models.TextField(blank=True, null=True, verbose_name='video promujące iframe'),
        ),
    ]
