# Generated by Django 4.2.4 on 2024-02-09 07:19

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.manager
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamoforms', '0001_initial'),
        ('events', '0012_event_promo_movie_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa pakietu')),
            ],
            options={
                'verbose_name': 'pakiet',
                'verbose_name_plural': 'pakiety',
            },
        ),
        migrations.CreateModel(
            name='EventBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(verbose_name='zawartość')),
                (
                    'bundle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='events.bundle', verbose_name='pakiet'
                    ),
                ),
            ],
            options={
                'verbose_name': 'pakiet eventu',
                'verbose_name_plural': 'pakiety eventu',
                'ordering': ['order'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        BtreeGistExtension(),
        migrations.CreateModel(
            name='EventBundlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cena')),
                (
                    'activity_range',
                    django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='obowiązujące daty'),
                ),
                (
                    'event_bundle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='events.eventbundle'
                    ),
                ),
            ],
            options={
                'verbose_name': 'koszt pakietu',
                'verbose_name_plural': 'koszty pakietu',
                'ordering': ['order'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': 'wydarzenie', 'verbose_name_plural': 'wydarzenia'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='form_html',
        ),
        migrations.RemoveField(
            model_name='event',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='prices',
        ),
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='dynamoforms.form',
                verbose_name='formularz wydarzenia',
            ),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='telefon'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_answers',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='registration',
                to='dynamoforms.useranswers',
                verbose_name='odpowiedzi klienta',
            ),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='kod'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='registrations',
                to='events.event',
                verbose_name='wydarzenie',
            ),
        ),
        migrations.DeleteModel(
            name='EventPrice',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='eventbundle',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_bundles',
                to='events.event',
                verbose_name='wydarzenie',
            ),
        ),
        migrations.AddField(
            model_name='registration',
            name='selected_bundle',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventbundle'
            ),
        ),
        migrations.AddConstraint(
            model_name='eventbundleprice',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[('activity_range', '&&'), ('event_bundle', '=')], name='exclude overlapping activity range'
            ),
        ),
        migrations.AddConstraint(
            model_name='eventbundle',
            constraint=models.UniqueConstraint(fields=('event', 'bundle', 'is_active'), name='unique event bundle'),
        ),
    ]
