# Generated by Django 4.2.4 on 2024-02-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_bundle_eventbundle_eventbundleprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplanitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='tytuł'),
        ),
    ]
