# Generated by Django 4.2.4 on 2024-02-27 14:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventplanitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBundleCodeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, verbose_name='kod rabatowy')),
                (
                    'discount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='zniżka w zł'),
                ),
                (
                    'event_bundle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='discounts',
                        to='events.eventbundle',
                        verbose_name='pakiet wydarzenia',
                    ),
                ),
            ],
            options={
                'verbose_name': 'kod rabatowy',
                'verbose_name_plural': 'kody rabatowe',
                'unique_together': {('code', 'event_bundle')},
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='eventbundleprice',
            name='event_bundle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prices',
                to='events.eventbundle',
                verbose_name='pakiet wydarzenia',
            ),
        ),
        migrations.AlterField(
            model_name='registration',
            name='selected_bundle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='events.eventbundle',
                verbose_name='wybrany pakiet',
            ),
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.AddField(
            model_name='registration',
            name='selected_code_discount',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='events.eventbundlecodediscount',
                verbose_name='wybrany kod rabatowy',
            ),
        ),
    ]
