# Generated by Django 4.2.4 on 2024-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_privacy_policy_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpartner',
            name='featured',
            field=models.BooleanField(
                default=False, help_text='partner pojawi się na górze strony', verbose_name='wyróżniony'
            ),
        ),
    ]
