# Generated by Django 4.2.4 on 2024-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventpartner_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpartner',
            name='featured',
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
    ]
