# Generated by Django 4.2.4 on 2024-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_eventpartner_featured_partner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_no_available_places_info',
            field=models.BooleanField(default=False, verbose_name='pokaż komunikat o braku wolnych miejsc'),
        ),
    ]
