# Generated by Django 4.2.4 on 2024-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_show_no_available_places_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbundle',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='jest wyprzedane'),
        ),
    ]
