# Generated by Django 4.2.4 on 2024-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0020_eventbundle_is_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='partners_text',
            field=models.CharField(blank=True, null=True, verbose_name='tekst sekcja partnerzy'),
        ),
    ]
