# Generated by Django 4.2.4 on 2024-08-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_partners_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='logo'),
        ),
    ]
