# Generated by Django 4.2.4 on 2024-09-25 18:49

import apps.events.utils
import ckeditor_uploader.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dynamoforms', '0003_alter_answer_options_alter_field_options_and_more'),
        ('events', '0022_event_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'verbose_name': 'bundle', 'verbose_name_plural': 'bundles'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'counter', 'verbose_name_plural': 'counters'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventbundle',
            options={'ordering': ['order'], 'verbose_name': 'event bundle', 'verbose_name_plural': 'event bundles'},
        ),
        migrations.AlterModelOptions(
            name='eventbundlecodediscount',
            options={'verbose_name': 'discount code', 'verbose_name_plural': 'discount codes'},
        ),
        migrations.AlterModelOptions(
            name='eventbundleprice',
            options={'ordering': ['order'], 'verbose_name': 'bundle cost', 'verbose_name_plural': 'bundle costs'},
        ),
        migrations.AlterModelOptions(
            name='eventcounter',
            options={'ordering': ['order'], 'verbose_name': 'event counter', 'verbose_name_plural': 'event counters'},
        ),
        migrations.AlterModelOptions(
            name='eventpartner',
            options={'ordering': ['order'], 'verbose_name': 'event partner', 'verbose_name_plural': 'event partners'},
        ),
        migrations.AlterModelOptions(
            name='eventplanitem',
            options={'ordering': ['order'], 'verbose_name': 'plan item', 'verbose_name_plural': 'plan items'},
        ),
        migrations.AlterModelOptions(
            name='eventspeaker',
            options={'ordering': ['order'], 'verbose_name': 'event speaker', 'verbose_name_plural': 'event speakers'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-date'], 'verbose_name': 'registration', 'verbose_name_plural': 'registrations'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'speaker', 'verbose_name_plural': 'speakers'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AddField(
            model_name='event',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='footer text'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='bundle name'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='event contents'),
        ),
        migrations.AlterField(
            model_name='event',
            name='counters',
            field=models.ManyToManyField(blank=True, through='events.EventCounter', to='events.counter', verbose_name='counters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='facebook page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamoforms.form', verbose_name='event form'),
        ),
        migrations.AlterField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='instagram page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_registrations',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum number of registrations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, through='events.EventPartner', to='events.partner', verbose_name='partners'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='partners section text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='privacy policy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy_policy_checkbox',
            field=models.TextField(blank=True, null=True, verbose_name='consent text in form'),
        ),
        migrations.AlterField(
            model_name='event',
            name='promo_movie_html',
            field=models.TextField(blank=True, null=True, verbose_name='promotional video iframe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='regulations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='regulations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='show_no_available_places_info',
            field=models.BooleanField(default=False, verbose_name='show message when no available places'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, through='events.EventSpeaker', to='events.speaker', verbose_name='speakers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True, verbose_name='tiktok page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='x_link',
            field=models.URLField(blank=True, null=True, verbose_name='x page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='youtube page'),
        ),
        migrations.AlterField(
            model_name='eventbundle',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.bundle', verbose_name='bundle'),
        ),
        migrations.AlterField(
            model_name='eventbundle',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='eventbundle',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bundles', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventbundle',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='is sold out'),
        ),
        migrations.AlterField(
            model_name='eventbundlecodediscount',
            name='code',
            field=models.CharField(max_length=50, verbose_name='discount code'),
        ),
        migrations.AlterField(
            model_name='eventbundlecodediscount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='discount in PLN'),
        ),
        migrations.AlterField(
            model_name='eventbundlecodediscount',
            name='event_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='events.eventbundle', verbose_name='event bundle'),
        ),
        migrations.AlterField(
            model_name='eventbundleprice',
            name='activity_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='valid dates'),
        ),
        migrations.AlterField(
            model_name='eventbundleprice',
            name='event_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='events.eventbundle', verbose_name='event bundle'),
        ),
        migrations.AlterField(
            model_name='eventbundleprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='eventbundleprice',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventcounter',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.counter', verbose_name='counter'),
        ),
        migrations.AlterField(
            model_name='eventcounter',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_counters', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventpartner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_partners', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventplanitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='eventplanitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventplanitem',
            name='hours',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='hours'),
        ),
        migrations.AlterField(
            model_name='eventplanitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plan/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventplanitem',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.speaker', verbose_name='speaker'),
        ),
        migrations.AlterField(
            model_name='eventplanitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.speaker', verbose_name='speaker'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='entry',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='entry'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='paid amount'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='responses',
            field=models.TextField(blank=True, null=True, verbose_name='responses'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='selected_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventbundle', verbose_name='selected bundle'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='selected_code_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventbundlecodediscount', verbose_name='selected discount code'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='unique_code',
            field=models.CharField(default=apps.events.utils.generate_unique_code, max_length=50, unique=True, verbose_name='unique code'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='dynamoforms.useranswers', verbose_name='customer answers'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='iframe_url',
            field=models.URLField(verbose_name='iframe URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_vertical',
            field=models.BooleanField(default=False, verbose_name='vertical'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='thumbnail'),
        ),
    ]
