# Generated by Django 5.1.3 on 2024-11-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                (
                    'field_type',
                    models.CharField(
                        choices=[('text', 'Text Field'), ('radio', 'Select')],
                        default='text',
                        max_length=15,
                        verbose_name='type',
                    ),
                ),
                ('required', models.BooleanField(default=False, verbose_name='required')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user answers',
                'verbose_name_plural': 'user answers',
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True)),
                ('choice', models.CharField(max_length=200, verbose_name='choice')),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='choices',
                        to='dynamo_forms.field',
                        verbose_name='field',
                    ),
                ),
            ],
            options={
                'verbose_name': 'field choice',
                'verbose_name_plural': 'field choices',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                (
                    'field_choice',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sections',
                        to='dynamo_forms.fieldchoice',
                        verbose_name='linked choice',
                    ),
                ),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sections',
                        to='dynamo_forms.form',
                        verbose_name='form',
                    ),
                ),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='field',
            name='section',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fields',
                to='dynamo_forms.section',
                verbose_name='section',
            ),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='answer')),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='dynamo_forms.field', verbose_name='field'
                    ),
                ),
                (
                    'user_answers',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='answers',
                        to='dynamo_forms.useranswers',
                        verbose_name='user answers',
                    ),
                ),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
    ]
