version: "3.9"

x-common-envs: &common-envs
   EVENT_TOOL_ALLOWED_HOSTS: ${EVENT_TOOL_ALLOWED_HOSTS}
   EVENT_TOOL_BASE_URL: ${EVENT_TOOL_BASE_URL}
   EVENT_TOOL_CSRF_COOKIE_DOMAIN: ${EVENT_TOOL_CSRF_COOKIE_DOMAIN}
   EVENT_TOOL_CSRF_TRUSTED_ORIGINS: ${EVENT_TOOL_CSRF_TRUSTED_ORIGINS}
   EVENT_TOOL_DEBUG: ${EVENT_TOOL_DEBUG}
   EVENT_TOOL_DEFAULT_FROM_EMAIL: ${EVENT_TOOL_DEFAULT_FROM_EMAIL}
   EVENT_TOOL_EMAIL_BACKEND: ${EVENT_TOOL_EMAIL_BACKEND}
   EVENT_TOOL_EMAIL_HOST: ${EVENT_TOOL_EMAIL_HOST}
   EVENT_TOOL_EMAIL_HOST_PASSWORD: ${EVENT_TOOL_EMAIL_HOST_PASSWORD}
   EVENT_TOOL_EMAIL_HOST_USER: ${EVENT_TOOL_EMAIL_HOST_USER}
   EVENT_TOOL_EMAIL_PORT: ${EVENT_TOOL_EMAIL_PORT}
   EVENT_TOOL_EMAIL_USE_SSL: ${EVENT_TOOL_EMAIL_USE_SSL}
   EVENT_TOOL_MEDIA_ROOT: ${EVENT_TOOL_MEDIA_ROOT}
   EVENT_TOOL_NEW_REGISTRATIONS_EMAIL_RECEIVERS: ${EVENT_TOOL_NEW_REGISTRATIONS_EMAIL_RECEIVERS}
   EVENT_TOOL_SECRETKEY: ${EVENT_TOOL_SECRETKEY}
   EVENT_TOOL_STATIC_ROOT: ${EVENT_TOOL_STATIC_ROOT}
   EVENT_TOOL_TPAY_MERCHANT_ID: ${EVENT_TOOL_TPAY_MERCHANT_ID}
   EVENT_TOOL_TPAY_MERCHANT_SECURITY_CODE: ${EVENT_TOOL_TPAY_MERCHANT_SECURITY_CODE}
   DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
   POSTGRES_DB: ${POSTGRES_DB}
   POSTGRES_DBHOST: ${POSTGRES_DBHOST}
   POSTGRES_DBPORT: ${POSTGRES_DBPORT}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_USER: ${POSTGRES_USER}
   SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
services:
  nginx:
    image: registry.dev.me/nginx/nginx:2
    healthcheck:
      test: curl --fail -s http://localhost:80/static/admin/css/base.css || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - event_tool.pl_data_static:/usr/share/nginx/html/static:ro
      - event_tool.pl_data_media:/usr/share/nginx/html/media:ro
      - nginx_configs.dev.me_data:/etc/nginx/conf.d/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.02"
          memory: "50M"
        reservations:
          cpus: "0.01"
          memory: "25M"
      update_config:
        delay: 10s
        parallelism: 1
        order: start-first
        failure_action: rollback
    ports:
      - "9039:80"
    networks:
      - event_tool_network

  web:
    image: registry.dev.me/event_tool/event_tool:${_VERSION}
    healthcheck:
      test: curl --fail -s http://localhost:8000/ || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - event_tool.pl_data_static:/app/static
      - event_tool.pl_data_media:/app/media
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - logstorage.dev.me_data:/logs
    environment:
      <<: *common-envs
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.20"
          memory: "200M"
        reservations:
          cpus: "0.10"
          memory: "100M"
      update_config:
        delay: 10s
        parallelism: 1
        order: start-first
        failure_action: rollback
    entrypoint: /prod/web/entrypoint.sh
    ports:
      - "9040:8000"
    networks:
      - event_tool_network
    extra_hosts:
      - "postgresql:10.16.86.30"

networks:
  event_tool_network:
    external: true

volumes:
  event_tool.pl_data_static:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /storage/swarm-storage/event_tool.pl_data_static

  event_tool.pl_data_media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /storage/swarm-storage/event_tool.pl_data_media

  nginx_configs.dev.me_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /storage/swarm-storage/nginx_configs

  logstorage.dev.me_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /storage/swarm-storage/logstorage.dev.me_data