# Generated by Django 4.2.4 on 2024-02-09 07:19

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('label', models.CharField(max_length=100, verbose_name='etykieta')),
                (
                    'field_type',
                    models.CharField(
                        choices=[
                            ('text', 'Pole tekstowe'),
                            ('select', 'Wybór'),
                            ('multiple_select', 'Wybór wielokrotny'),
                        ],
                        default='text',
                        max_length=15,
                        verbose_name='typ',
                    ),
                ),
                ('required', models.BooleanField(default=False, verbose_name='wymagane')),
            ],
            options={
                'verbose_name': 'pole',
                'verbose_name_plural': 'pola',
                'ordering': ['order'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True)),
                ('choice', models.CharField(max_length=200, verbose_name='opcja')),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='choices',
                        to='dynamoforms.field',
                        verbose_name='pole',
                    ),
                ),
            ],
            options={
                'verbose_name': 'pole do wyboru',
                'verbose_name_plural': 'pola do wyboru',
                'ordering': ['order'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'formularz',
                'verbose_name_plural': 'formularze',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'odpowiedzi użytkownika',
                'verbose_name_plural': 'odpowiedzi użytkownika',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='nazwa')),
                (
                    'field_choice',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sections',
                        to='dynamoforms.fieldchoice',
                        verbose_name='powiązana odpowiedź',
                    ),
                ),
                (
                    'form',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sections',
                        to='dynamoforms.form',
                        verbose_name='formularz',
                    ),
                ),
            ],
            options={
                'verbose_name': 'sekcja',
                'verbose_name_plural': 'sekcje',
                'ordering': ['order'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='section',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fields',
                to='dynamoforms.section',
                verbose_name='sekcja',
            ),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='odpowiedź')),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='dynamoforms.field', verbose_name='pole'
                    ),
                ),
                (
                    'user_answers',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='dynamoforms.useranswers',
                        verbose_name='odpowiedzi użytkownika',
                    ),
                ),
            ],
            options={
                'verbose_name': 'odpowiedź',
                'verbose_name_plural': 'odpowiedzi',
            },
        ),
    ]
