# Generated by Django 4.2.4 on 2024-02-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamoforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_answers',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='answers',
                to='dynamoforms.useranswers',
                verbose_name='odpowiedzi użytkownika',
            ),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(
                choices=[('text', 'Pole tekstowe'), ('select', 'Wybór')],
                default='text',
                max_length=15,
                verbose_name='typ',
            ),
        ),
    ]
