# Generated by Django 4.2.4 on 2024-09-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamoforms', '0002_alter_answer_user_answers_alter_field_field_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order'], 'verbose_name': 'field', 'verbose_name_plural': 'fields'},
        ),
        migrations.AlterModelOptions(
            name='fieldchoice',
            options={'ordering': ['order'], 'verbose_name': 'field choice', 'verbose_name_plural': 'field choices'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'form', 'verbose_name_plural': 'forms'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='useranswers',
            options={'verbose_name': 'user answers', 'verbose_name_plural': 'user answers'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dynamoforms.field', verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='dynamoforms.useranswers', verbose_name='user answers'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Field'), ('select', 'Select')], default='text', max_length=15, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.CharField(max_length=100, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamoforms.section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='choice',
            field=models.CharField(max_length=200, verbose_name='choice'),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dynamoforms.field', verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='field_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='dynamoforms.fieldchoice', verbose_name='linked choice'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dynamoforms.form', verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='name'),
        ),
    ]
