# Generated by Django 5.1.3 on 2024-11-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                (
                    'script_type',
                    models.CharField(
                        choices=[('required', 'Required'), ('marketing', 'Marketing'), ('analytics', 'Analytics')],
                        max_length=50,
                    ),
                ),
                (
                    'service',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_manager.service'),
                ),
            ],
        ),
    ]
