name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Create event_tool dev network"
      run: docker network create event_tool_dev_network
    - name: "Build images and start containers"
      run: docker compose -f "docker-compose.yml" up -d --build
    - name: "Check all migrations files are created"
      run: docker compose -f "docker-compose.yml" run -T web python manage.py makemigrations --check --dry-run
    - name: "Run tests"
      run: docker compose -f "docker-compose.yml" run -T web python manage.py test -v2 --noinput --settings event_tool.settings.docker