name: Linters

on:
  pull_request:
    branches: [ master ]

jobs:

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install isort
        run: |
          python -m pip install --upgrade pip
          pip install isort

      - name: Check format with isort
        run: |
          isort . --diff --check-only

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check format with black
        run: |
          black . --diff --check

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get python files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            py:
              - '**/*.py'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-bugbear flake8-comprehensions flake8-tuple flake8-simplify flake8-variables-names flake8-django flake8-bandit

      - name: Run flake8 if python file(s) change
        if: steps.changed-files-yaml.outputs.py_any_changed == 'true'
        run: |
          echo "One or more python file(s) has changed."
          flake8 ${{ steps.changed-files-yaml.outputs.py_all_changed_files }} --enable-extensions=BUGBEAR,COMPREHENSIONS,TUPLE,SIMPLIFY,VARIABLENAMES,DJANGO,BANDIT

  double-quote-string-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run double-quote-string-fixer
        run: pre-commit run double-quote-string-fixer --all-files

  trailing-whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run trailing-whitespace
        run: pre-commit run trailing-whitespace --all-files

  end-of-file-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run end-of-file-fixer
        run: pre-commit run end-of-file-fixer --all-files
